In [12]:
from datetime import datetime, timedelta
from os import getenv

import numpy as np
import pandas as pd
from joblib import load

from utils import calculate_indicators_for_prediction_modul, get_candles, get_stocks

In [13]:
# загружаем модель
tickers, model = load('stocks_analyser_tickers_with_model.joblib')

In [14]:
# выгружаю токен для т-инвестиций
TOKEN = getenv("t_bank_token")
# P.S: если захотите воспользоваться этим модулем, вам придётся создать свой токен на сайте т-банка
# и записать его в эту переменную в таком формате: TOKEN = "ваш_токен"

In [15]:
# получаем данные по акциям
stocks = await get_stocks(TOKEN)

In [16]:
# создаем диапозон дат за 70 дней
end_date = datetime.now()
start_date = end_date - timedelta(days=70)

# выгружаем свечи в этом дипазоне
candles_df = await get_candles(TOKEN, stocks, tickers, start_date, end_date)
candles_df = candles_df.sort_values(['ticker', 'date']).reset_index(drop=True)

Запрашиваем данные с 2026-05-31 по 2026-08-09
Всего тикеров: 153

In [17]:
# фильтруем акции по обученному списку тикеров
candles_df = candles_df[candles_df.ticker.isin(tickers)]
# проводим форматирование даты
candles_df.date = pd.to_datetime(candles_df.date)
# формируем признаки
candles_df = calculate_indicators_for_prediction_modul(candles_df)

In [18]:
# удаляем бесконечности и NaN
candles_df.replace([np.inf, -np.inf], np.nan, inplace=True)
candles_df.dropna(inplace=True)
# смотрим результат
candles_df

,ticker,sector,date,open,high,low,close,volume,return,atr,...,signal,hist,williams_r,vol_ewma,vol_asym,log_vol,volatility_20,volatility_60,momentum,ad_line
39,AFKS,financial,2026-07-11,9.47,9.50,9.30,9.31,146001,-0.017932,0.591624,...,-0.568846,-0.220833,-96.935933,0.031849,0.040314,-6.893475,0.034256,0.031880,0.932866,2.243718e+06
40,AFKS,financial,2026-07-12,9.31,9.45,9.29,9.43,54480,0.012889,0.560793,...,-0.616090,-0.188976,-93.593315,0.031464,0.039099,-6.917814,0.033600,0.031614,0.944890,2.284578e+06
41,AFKS,financial,2026-07-13,9.41,9.82,9.28,9.49,1576860,0.006363,0.559308,...,-0.653504,-0.149657,-91.922006,0.030735,0.037829,-6.964694,0.033902,0.031274,0.945219,1.934164e+06
42,AFKS,financial,2026-07-14,9.46,9.58,9.35,9.41,529346,-0.008430,0.535786,...,-0.682582,-0.116314,-91.428571,0.029712,0.036668,-7.032393,0.032165,0.030894,0.975130,1.680999e+06
43,AFKS,financial,2026-07-15,9.40,9.44,8.81,8.81,1660558,-0.063762,0.542516,...,-0.712929,-0.121386,-100.000000,0.031958,0.040994,-6.886676,0.033491,0.031876,0.929325,2.044097e+04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5087,YDEX,it,2026-08-05,3963.00,4050.00,3951.50,4043.50,714207,0.020313,129.310579,...,68.704214,37.834896,-1.058632,0.023192,0.025217,-7.527909,0.026706,0.022662,1.020055,8.506680e+05
5088,YDEX,it,2026-08-06,4046.50,4066.50,3978.00,4039.50,607155,-0.000989,126.395538,...,77.340324,34.544442,-5.094340,0.022513,0.024427,-7.587336,0.025697,0.022624,1.040438,1.087356e+06
5089,YDEX,it,2026-08-07,4044.00,4055.50,3940.50,3947.50,521029,-0.022775,125.581571,...,83.364037,24.094850,-22.709924,0.022843,0.024678,-7.558261,0.022854,0.022806,1.009720,6.297561e+05
5090,YDEX,it,2026-08-08,3965.00,4003.50,3951.50,3995.50,50872,0.012160,120.611459,...,88.010384,18.585391,-13.549618,0.022236,0.024092,-7.612059,0.021865,0.022803,1.005410,6.649752e+05
5091,YDEX,it,2026-08-09,3996.00,4009.50,3995.50,4008.00,20609,0.003129,112.996354,...,91.548694,14.153238,-21.234120,0.021540,0.023351,-7.675678,0.021929,0.022804,1.011355,6.811680e+05

In [ ]:
# выставляем выбраный при обучение порог
threshold = 0.679298

In [20]:
# убираем колонки, которые нельзя использовать в обучении + те, которые мешали во время обучения
columns_to_drop =  ['index', 'date','ticker', 'sector','return']

In [ ]:
# формируем предсказания
pred = model.predict_proba(candles_df.drop(columns=columns_to_drop, errors='ignore'))[:,1] > threshold

In [ ]:
# выводим предсказание на текущий день
candles_df[pred & (candles_df.date.dt.date == datetime.now().date())]

Empty DataFrame
Columns: [ticker, sector, date, open, high, low, close, volume, return, atr, obv, stoch_k, stoch_d, volume_ratio, rsi, ema_12, ema_26, sma_10, sma_40, sma10_vs_sma40, cci_20, macd, signal, hist, williams_r, vol_ewma, vol_asym, log_vol, volatility_20, volatility_60, momentum, ad_line]
Index: []

[0 rows x 32 columns]