In [73]:
from datetime import datetime, timedelta
from os import getenv

import numpy as np
import pandas as pd
from joblib import load

from utils import calculate_indicators_for_prediction_modul, get_candles, get_stocks

In [74]:
# загружаем модель
tickers, model = load('stocks_analyser_tickers_with_model.joblib')

In [75]:
# выгружаю токен для т-инвестиций
TOKEN = getenv("t_bank_token")
# P.S: если захотите воспользоваться этим модулем, вам придётся создать свой токен на сайте т-банка
# и записать его в эту переменную в таком формате: TOKEN = "ваш_токен"

In [76]:
# получаем данные по акциям
stocks = await get_stocks(TOKEN)

In [77]:
# создаем диапозон дат за 70 дней
end_date = datetime.now()
start_date = end_date - timedelta(days=70)

# выгружаем свечи в этом дипазоне
candles_df = await get_candles(TOKEN, stocks, tickers, start_date, end_date)
candles_df = candles_df.sort_values(['ticker', 'date']).reset_index(drop=True)

Запрашиваем данные с 2026-06-11 по 2026-08-20
Всего тикеров: 153

In [78]:
# фильтруем акции по обученному списку тикеров
candles_df = candles_df[candles_df.ticker.isin(tickers)]
# проводим форматирование даты
candles_df.date = pd.to_datetime(candles_df.date)
# формируем признаки
candles_df = calculate_indicators_for_prediction_modul(candles_df)

In [79]:
# удаляем бесконечности и NaN
candles_df.replace([np.inf, -np.inf], np.nan, inplace=True)
candles_df.dropna(inplace=True)
# смотрим результат
candles_df

,ticker,sector,date,open,high,low,close,volume,return,atr,...,signal,hist,williams_r,vol_ewma,vol_asym,log_vol,volatility_20,volatility_60,momentum,ad_line
39,AFKS,financial,2026-07-22,8.81,9.11,8.50,8.95,2419160,0.015891,0.613430,...,-1.110840,0.114215,-42.810458,0.045133,0.051731,-6.196288,0.044727,0.038578,1.185430,-4.206072e+06
40,AFKS,financial,2026-07-23,8.95,9.05,8.43,8.46,1897457,-0.054749,0.613899,...,-1.078494,0.129384,-51.908397,0.045390,0.053041,-6.184915,0.045894,0.038785,1.113158,-5.919904e+06
41,AFKS,financial,2026-07-24,8.40,8.90,8.14,8.73,4683675,0.031915,0.624335,...,-1.038701,0.159172,-41.603053,0.045084,0.051898,-6.198466,0.046904,0.038864,1.122108,-3.331557e+06
42,AFKS,financial,2026-07-25,8.78,8.92,8.76,8.80,235813,0.008018,0.593311,...,-0.992842,0.183436,-38.931298,0.043744,0.050216,-6.258807,0.046737,0.038486,1.035294,-3.449464e+06
43,AFKS,financial,2026-07-26,8.78,8.81,8.57,8.68,283726,-0.013636,0.568074,...,-0.945236,0.190421,-43.511450,0.042334,0.048745,-6.324339,0.042974,0.038030,0.985244,-3.473108e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4935,YDEX,it,2026-08-14,3831.50,3868.00,3650.00,3683.00,899777,-0.036872,115.675715,...,80.585354,-31.400424,-92.076831,0.022866,0.025669,-7.556232,0.022253,0.023347,0.918912,-3.954125e+05
4936,YDEX,it,2026-08-17,3692.50,3692.50,3555.00,3592.00,943051,-0.024708,117.234593,...,68.715471,-47.479534,-92.766373,0.022829,0.026005,-7.559449,0.017947,0.023539,0.898112,-8.309306e+05
4937,YDEX,it,2026-08-18,3598.00,3762.50,3586.50,3760.00,898804,0.046771,121.432122,...,57.472033,-44.973751,-59.921799,0.025218,0.027636,-7.360424,0.021084,0.024325,0.938124,4.233915e+04
4938,YDEX,it,2026-08-19,3762.00,3777.50,3655.00,3725.50,585368,-0.009176,121.508399,...,46.529221,-43.771248,-66.666667,0.024513,0.026915,-7.417098,0.020817,0.024343,0.938886,1.307417e+05
4939,YDEX,it,2026-08-20,3725.50,3748.50,3590.00,3604.00,609874,-0.032613,124.150656,...,34.303965,-48.901025,-90.420332,0.024994,0.027955,-7.378273,0.021884,0.024599,0.942469,-3.713943e+05

In [ ]:
# выставляем выбраный при обучение порог
threshold = 0.652711

In [86]:
# убираем колонки, которые нельзя использовать в обучении + те, которые мешали во время обучения
columns_to_drop =  ['index', 'date','ticker', 'sector','return']

In [87]:
# формируем предсказания
pred = model.predict_proba(candles_df.drop(columns=columns_to_drop, errors='ignore'))[:,1] > threshold

In [88]:
# выводим предсказание на текущий день
candles_df[pred & (candles_df.date.dt.date == datetime.now().date())]

,ticker,sector,date,open,high,low,close,volume,return,atr,...,signal,hist,williams_r,vol_ewma,vol_asym,log_vol,volatility_20,volatility_60,momentum,ad_line
4744,VTBR,financial,2026-08-20,53.98,54.59,52.48,52.86,47484232,-0.018931,1.995519,...,-1.869654,0.001597,-89.711934,0.029369,0.033991,-7.05564,0.020555,0.033575,0.952604,-4.194386e+08