In [41]:
import pandas as pd
import numpy as np
from os import getenv
from joblib import load
from datetime import datetime, timedelta
from utils import get_stocks, get_candles, calculate_indicators_for_prediction_modul

In [42]:
tickers , dv, model = load('stocks_analyser_tickers_dv_with_model.joblib')

In [43]:
# выгружаю токен для т-инвестиций
TOKEN = getenv("t_bank_token")
# P.S: если захотите воспользоваться этим модулем, вам придётся создать свой токен на сайте т-банка
# и записать его в эту переменную в таком формате: TOKEN = "ваш_токен"

In [44]:
# получаем данные по акциям
stocks = await get_stocks(TOKEN)

In [45]:
# создаем диапозон дат за 70 дней
end_date = datetime.now()
start_date = end_date - timedelta(days=70)

# выгружаем свечи в этом дипазоне
candles_df = await get_candles(TOKEN, stocks, start_date, end_date)
candles_df = candles_df.sort_values(['ticker', 'date']).reset_index(drop=True)

Запрашиваем данные с 2026-05-04 по 2026-07-13
Всего тикеров: 153
Успешно добавлен VSMO в результат
Успешно добавлен UNAC в результат
Успешно добавлен CNRU в результат
Успешно добавлен VKCO в результат
Успешно добавлен MGNT в результат
Успешно добавлен KZOSP в результат
Успешно добавлен WUSH в результат
Успешно добавлен UGLD в результат
Успешно добавлен SELG в результат
Успешно добавлен PRFN в результат
Успешно добавлен CARM в результат
Успешно добавлен RUAL в результат
Успешно добавлен NKHP в результат
Успешно добавлен ALRS в результат
Успешно добавлен DIAS в результат
Успешно добавлен TATN в результат
Успешно добавлен RTKM в результат
Успешно добавлен PRMD в результат
Успешно добавлен TGKN в результат
Успешно добавлен TRNFP в результат
Успешно добавлен DOMRF в результат
Успешно добавлен RAGR в результат
Успешно добавлен GCHE в результат
Успешно добавлен UWGN в результат
Успешно добавлен SNGSP в результат
Успешно добавлен FIXR в результат
Успешно добавлен NKNC в результат
Успешно добавлен VRSB в результат
Успешно добавлен MBNK в результат
Успешно добавлен MOEX в результат
Успешно добавлен KAZTP в результат
Успешно добавлен SNGS в результат
Успешно добавлен TGKBP в результат
Успешно добавлен PIKK в результат
Успешно добавлен ROSN в результат
Успешно добавлен EUTR в результат
Успешно добавлен MRKU в результат
Успешно добавлен ENPG в результат
Успешно добавлен T в результат
Успешно добавлен MRKV в результат
Успешно добавлен CNTL в результат
Успешно добавлен VSEH в результат
Успешно добавлен SVAV в результат
Успешно добавлен KMAZ в результат
Успешно добавлен KZOS в результат
Успешно добавлен ELFV в результат
Успешно добавлен HEAD в результат
Успешно добавлен ETLN в результат
Успешно добавлен SMLT в результат
Успешно добавлен SBER в результат
Успешно добавлен GECO в результат
Успешно добавлен GAZP в результат
Успешно добавлен BSPB в результат
Успешно добавлен LSNG в результат
Успешно добавлен RENI в результат
Успешно добавлен POSI в результат
Успешно добавлен KROT в результат
Успешно добавлен SIBN в результат
Успешно добавлен KLSB в результат
Успешно добавлен CHMK в результат
Успешно добавлен MRKZ в результат
Успешно добавлен APTK в результат
Успешно добавлен HYDR в результат
Успешно добавлен SFIN в результат
Успешно добавлен RASP в результат
Успешно добавлен BAZA в результат
Успешно добавлен GMKN в результат
Успешно добавлен UPRO в результат
Успешно добавлен MSNG в результат
Успешно добавлен AFKS в результат
Успешно добавлен PLZL в результат
Успешно добавлен LEAS в результат
Успешно добавлен CNTLP в результат
Успешно добавлен OZON в результат
Успешно добавлен LIFE в результат
Успешно добавлен DATA в результат
Успешно добавлен IRKT в результат
Успешно добавлен TTLK в результат
Успешно добавлен SVCB в результат
Успешно добавлен GEMC в результат
Успешно добавлен PHOR в результат
Успешно добавлен HNFG в результат
Успешно добавлен TATNP в результат
Успешно добавлен MAGN в результат
Успешно добавлен VTBR в результат
Успешно добавлен BANEP в результат
Успешно добавлен MRKP в результат
Успешно добавлен FLOT в результат
Успешно добавлен ABIO в результат
Успешно добавлен DVEC в результат
Успешно добавлен ZAYM в результат
Успешно добавлен MTSS в результат
Успешно добавлен OZPH в результат
Успешно добавлен FEES в результат
Успешно добавлен PMSB в результат
Успешно добавлен GLRX в результат
Успешно добавлен RBCM в результат
Успешно добавлен MSRS в результат
Успешно добавлен IRAO в результат
Успешно добавлен NSVZ в результат
Успешно добавлен BLNG в результат
Успешно добавлен X5 в результат
Успешно добавлен NVTK в результат
Успешно добавлен UNKL в результат
Успешно добавлен AQUA в результат
Успешно добавлен ROLO в результат
Успешно добавлен OGKB в результат
Успешно добавлен CBOM в результат
Успешно добавлен ABRD в результат
Успешно добавлен TRMK в результат
Успешно добавлен SOFL в результат
Успешно добавлен KRKNP в результат
Успешно добавлен CHMF в результат
Успешно добавлен NKNCP в результат
Успешно добавлен LSRG в результат
Успешно добавлен RTKMP в результат
Успешно добавлен MGTSP в результат
Успешно добавлен KLVZ в результат
Успешно добавлен YDEX в результат
Успешно добавлен BANE в результат
Успешно добавлен AFLT в результат
Успешно добавлен MVID в результат
Успешно добавлен PMSBP в результат
Успешно добавлен MSTT в результат
Успешно добавлен MTLR в результат
Успешно добавлен IVAT в результат
Успешно добавлен AKRN в результат
Успешно добавлен MDMG в результат
Успешно добавлен SBERP в результат
Успешно добавлен LENT в результат
Успешно добавлен ASTR в результат
Успешно добавлен RKKE в результат
Успешно добавлен MRKC в результат
Успешно добавлен KAZT в результат
Успешно добавлен YAKG в результат
Успешно добавлен TGKB в результат
Успешно добавлен RNFT в результат
Успешно добавлен GTRK в результат
Успешно добавлен NLMK в результат
Успешно добавлен BELU в результат
Успешно добавлен FESH в результат
Успешно добавлен SGZH в результат
Успешно добавлен LSNGP в результат
Успешно добавлен MRKS в результат
Успешно добавлен LKOH в результат
Успешно добавлен DELI в результат
Успешно добавлен MGKL в результат
Успешно добавлен INCB в результат
Успешно добавлен NMTP в результат
Успешно добавлен TGKA в результат
Успешно добавлен MTLRP в результат
Успешно добавлен BTBR в результат
Успешно добавлен MRKY в результат

In [46]:
candles_df

      ticker        date    open    high     low   close  volume
0       ABIO  2026-05-04   58.30   58.60   55.08   56.02   34953
1       ABIO  2026-05-05   56.04   56.56   54.52   55.58   15894
2       ABIO  2026-05-06   55.72   56.04   54.88   55.10   10694
3       ABIO  2026-05-07   54.88   55.14   54.46   54.64    6997
4       ABIO  2026-05-08   54.56   55.28   54.52   55.06    5622
...      ...         ...     ...     ...     ...     ...     ...
10188   ZAYM  2026-07-09  129.55  129.80  128.35  128.85    3908
10189   ZAYM  2026-07-10  130.35  130.35  128.25  128.90    4287
10190   ZAYM  2026-07-11  128.80  129.00  127.80  128.40    2264
10191   ZAYM  2026-07-12  128.95  129.30  128.50  129.30     373
10192   ZAYM  2026-07-13  129.35  129.95  129.00  129.80    1360

[10193 rows x 7 columns]

In [47]:
candles_df = calculate_indicators_for_prediction_modul(candles_df)

In [48]:
# удаляем бесконечности и NaN
candles_df.replace([np.inf, -np.inf], np.nan, inplace=True)
candles_df.dropna(inplace=True)
candles_df = candles_df[candles_df.ticker.isin(tickers)]
candles_df

,ticker,date,open,high,low,close,volume,atr,obv,stoch_k,...,volatility_20,volatility_60,vol_ratio_20_60,momentum,range_norm,range_ratio,open_close_ratio,volume_spike,ad_line,return
69,ABRD,2026-05-06,145.80,146.20,144.60,144.60,1268,6.458258,-2.249890e+05,57.917724,...,0.644543,0.374142,1.722722,3.845745,0.000000,1.011065,1.008299,0,-2.473628e+05,-0.001381
70,ABRD,2026-05-07,144.60,145.20,144.00,144.40,589,6.207865,-2.255780e+05,68.920507,...,0.644420,0.374143,1.722388,3.840426,0.333333,1.008333,1.001385,0,-2.475592e+05,-0.001383
71,ABRD,2026-05-08,143.80,144.40,143.60,144.20,1118,5.950347,-2.266960e+05,79.759802,...,0.644598,0.374164,1.722768,0.987671,0.750000,1.005571,0.997226,0,-2.470002e+05,-0.001385
72,ABRD,2026-05-11,144.80,145.60,143.80,145.00,556,5.752712,-2.261400e+05,89.514959,...,0.645083,0.374150,1.724128,1.001381,0.666667,1.012517,0.998621,0,-2.468148e+05,0.005548
73,ABRD,2026-05-12,144.40,146.00,144.00,145.00,2484,5.574011,-2.261400e+05,97.917419,...,0.645241,0.374150,1.724551,1.002766,0.500000,1.013889,0.995862,0,-2.468148e+05,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10188,ZAYM,2026-07-09,129.55,129.80,128.35,128.85,3908,15.811975,-3.363339e+09,6.960545,...,0.020224,0.015682,1.289645,0.972820,0.344828,1.011297,1.005433,0,-1.466487e+09,-0.000388
10189,ZAYM,2026-07-10,130.35,130.35,128.25,128.90,4287,15.159024,-3.363335e+09,8.022800,...,0.020263,0.015681,1.292189,0.990776,0.309524,1.016374,1.011249,0,-1.466489e+09,0.000388
10190,ZAYM,2026-07-11,128.80,129.00,127.80,128.40,2264,14.494308,-3.363337e+09,8.725244,...,0.020189,0.015682,1.287416,0.994578,0.500000,1.009390,1.003115,0,-1.466489e+09,-0.003879
10191,ZAYM,2026-07-12,128.95,129.30,128.50,129.30,373,13.846960,-3.363336e+09,9.674202,...,0.020357,0.015686,1.297791,1.003103,1.000000,1.006226,0.997293,0,-1.466488e+09,0.007009
10192,ZAYM,2026-07-13,129.35,129.95,129.00,129.80,1360,13.232819,-3.363335e+09,11.766582,...,0.020201,0.012507,1.615171,1.007373,0.842105,1.007364,0.996533,0,-1.466488e+09,0.003867

In [49]:
# проводим ручную фильтрацию по техническим индиакторам для тестовой выборки
candles_df = candles_df[
    (candles_df.sma10_vs_sma40 > 1.02) &
    (candles_df['hist'] > candles_df.signal) &
    (candles_df.stoch_k > candles_df.stoch_d) &
    (candles_df['volume_ratio'] > 1.2) &
    (candles_df['volume_spike'] == 1) &
    (candles_df['ema_12'] > candles_df['ema_26']) &
    (candles_df['price_vs_sma_10'] > 1.01)
    ]

In [50]:
# убираем колонки, которые нельзя использовать в обучении
features_col = [col for col in candles_df.columns if col not in ['index', 'open', 'high', 'low', 'close', 'volume','date']]

In [51]:
candles_dict = candles_df[features_col].to_dict(orient='records')
X = dv.transform(candles_dict)

In [66]:
proba = model.predict_proba(X)[:, 1] > 0.6

In [67]:
# Если есть свежие прогнозы, выводим их на экран
min_pos = (datetime.now() - timedelta(days=2)).date()
predictions = candles_df[proba & (candles_df.date == candles_df.date.max())].T

if (min_pos < candles_df.date.max()) & (len(predictions.T) > 0):
    display(predictions)
else:
    print("Нет прогнозов на эту дату")

Нет прогнозов на эту дату