In [20]:
from datetime import datetime, timedelta
from os import getenv

import numpy as np
import pandas as pd
from joblib import load

from utils import calculate_indicators_for_prediction_modul, get_candles, get_stocks

In [ ]:
# загружаем модель
tickers, model = load('stocks_analyser_tickers_with_model.joblib')

In [22]:
# выгружаю токен для т-инвестиций
TOKEN = getenv("t_bank_token")
# P.S: если захотите воспользоваться этим модулем, вам придётся создать свой токен на сайте т-банка
# и записать его в эту переменную в таком формате: TOKEN = "ваш_токен"

In [23]:
# получаем данные по акциям
stocks = await get_stocks(TOKEN)

In [24]:
# создаем диапозон дат за 70 дней
end_date = datetime.now()
start_date = end_date - timedelta(days=70)

# выгружаем свечи в этом дипазоне
candles_df = await get_candles(TOKEN, stocks, tickers, start_date, end_date)
candles_df = candles_df.sort_values(['ticker', 'date']).reset_index(drop=True)

Запрашиваем данные с 2026-05-24 по 2026-08-02
Всего тикеров: 153

In [ ]:
# фильтруем акции по обученному списку тикеров
candles_df = candles_df[candles_df.ticker.isin(tickers)]
# проводим форматирование даты
candles_df.date = pd.to_datetime(candles_df.date)
# формируем признаки
candles_df = calculate_indicators_for_prediction_modul(candles_df)

In [ ]:
# удаляем бесконечности и NaN
candles_df.replace([np.inf, -np.inf], np.nan, inplace=True)
candles_df.dropna(inplace=True)
# смотрим результат
candles_df

,ticker,sector,date,open,high,low,close,volume,season,volatility,...,volatility_20,volatility_60,vol_ratio_20_60,momentum,range_norm,range_ratio,open_close_ratio,volume_spike,ad_line,return
39,AKRN,materials,2026-07-04,15572.00,15764.00,15572.00,15764.00,8,summer,0.018526,...,0.019368,0.015004,1.290843,0.991696,1.000000,1.012330,0.987820,0,-1588.487574,0.007130
40,AKRN,materials,2026-07-05,15756.00,15782.00,15756.00,15782.00,23,summer,0.018526,...,0.019364,0.014839,1.304896,0.981712,1.000000,1.001650,0.998353,0,-1565.487574,0.001141
41,AKRN,materials,2026-07-06,15778.00,15880.00,15360.00,15450.00,267,summer,0.018526,...,0.019629,0.014883,1.318920,0.960463,0.173077,1.033854,1.021230,0,-1740.064497,-0.021261
42,AKRN,materials,2026-07-07,15300.00,15324.00,15006.00,15222.00,324,summer,0.018526,...,0.019335,0.014779,1.308225,0.979537,0.679245,1.021192,1.005124,0,-1623.913554,-0.014867
43,AKRN,materials,2026-07-08,15018.00,15462.00,15000.00,15210.00,237,summer,0.018526,...,0.019389,0.014618,1.326384,0.971761,0.454545,1.030800,0.987377,0,-1645.459008,-0.000789
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3412,ZAYM,financial,2026-07-27,131.95,133.45,130.50,132.80,5801,summer,0.014711,...,0.015921,0.015594,1.020983,1.012195,0.779661,1.022605,0.993599,0,28372.090264,0.006800
3413,ZAYM,financial,2026-07-28,132.75,132.90,131.35,131.80,3131,summer,0.014711,...,0.016037,0.015594,1.028349,1.009188,0.290323,1.011801,1.007208,0,27059.090264,-0.007559
3414,ZAYM,financial,2026-07-29,131.85,132.50,131.60,132.50,2202,summer,0.014711,...,0.016059,0.015596,1.029702,1.003408,1.000000,1.006839,0.995094,0,29261.090264,0.005297
3415,ZAYM,financial,2026-07-30,132.50,134.00,132.20,133.05,4386,summer,0.014711,...,0.016068,0.015612,1.029211,1.003772,0.472222,1.013616,0.995866,0,29017.423597,0.004142
3416,ZAYM,financial,2026-07-31,133.10,133.35,129.55,132.30,6075,summer,0.014711,...,0.016105,0.015618,1.031185,1.003033,0.723684,1.029332,1.006047,0,31735.186755,-0.005653

In [27]:
threshold = 0.529

In [28]:
# убираем колонки, которые нельзя использовать в обучении
columns_to_drop =  ['ticker', 'date', 'volatility','high', 'low', 'season', 'sector', 'open_close_ratio'
                    , 'volume_spike', 'ema_slope', 'rsi_slope', 'return', 'hist_slope', 'vol_ratio_20_60', 'volume_ratio']

In [29]:
pred = model.predict_proba(candles_df.drop(columns=columns_to_drop, errors='ignore'))[:,1] > threshold

In [34]:
candles_df[pred & (candles_df.date == datetime.now())]

Empty DataFrame
Columns: [ticker, sector, date, open, high, low, close, volume, season, volatility, atr, obv, stoch_k, stoch_d, volume_ratio, rsi, rsi_slope, ema_12, ema_26, ema_slope, sma_10, sma_40, price_vs_sma_10, sma10_vs_sma40, cci_20, macd, signal, hist, hist_slope, williams_r, vol_ewma, vol_asym, log_vol, volatility_20, volatility_60, vol_ratio_20_60, momentum, range_norm, range_ratio, open_close_ratio, volume_spike, ad_line, return]
Index: []

[0 rows x 43 columns]